project_id = "phdtvfooogqrjykhxqno"

[functions.generate-questions]
verify_jwt = false

[functions.speech-to-text]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.analyze-answer]
verify_jwt = false

[functions.final-analysis]
verify_jwt = false

[functions.generate-resources]
verify_jwt = false